version: "3.8"

services:
  db:
    container_name: db
    image: postgres:14
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always
  auth-service:
    container_name: auth-service
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    tty: true
    depends_on:
      - db
    restart: always